// Code generated by protoc-gen-go.
// source: protobuf/move.proto
// DO NOT EDIT!

/*
Package moveio is a generated protocol buffer package.

It is generated from these files:
	protobuf/move.proto

It has these top-level messages:
	MoveIORequest
	MoveIOResponse
*/
package moveio

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MoveIORequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *MoveIORequest) Reset()                    { *m = MoveIORequest{} }
func (m *MoveIORequest) String() string            { return proto.CompactTextString(m) }
func (*MoveIORequest) ProtoMessage()               {}
func (*MoveIORequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MoveIORequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type MoveIOResponse struct {
	Response string `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
}

func (m *MoveIOResponse) Reset()                    { *m = MoveIOResponse{} }
func (m *MoveIOResponse) String() string            { return proto.CompactTextString(m) }
func (*MoveIOResponse) ProtoMessage()               {}
func (*MoveIOResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MoveIOResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func init() {
	proto.RegisterType((*MoveIORequest)(nil), "moveio.MoveIORequest")
	proto.RegisterType((*MoveIOResponse)(nil), "moveio.MoveIOResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MoveService service

type MoveServiceClient interface {
	Move(ctx context.Context, in *MoveIORequest, opts ...grpc.CallOption) (*MoveIOResponse, error)
}

type moveServiceClient struct {
	cc *grpc.ClientConn
}

func NewMoveServiceClient(cc *grpc.ClientConn) MoveServiceClient {
	return &moveServiceClient{cc}
}

func (c *moveServiceClient) Move(ctx context.Context, in *MoveIORequest, opts ...grpc.CallOption) (*MoveIOResponse, error) {
	out := new(MoveIOResponse)
	err := grpc.Invoke(ctx, "/moveio.MoveService/Move", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MoveService service

type MoveServiceServer interface {
	Move(context.Context, *MoveIORequest) (*MoveIOResponse, error)
}

func RegisterMoveServiceServer(s *grpc.Server, srv MoveServiceServer) {
	s.RegisterService(&_MoveService_serviceDesc, srv)
}

func _MoveService_Move_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveIORequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoveServiceServer).Move(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/moveio.MoveService/Move",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoveServiceServer).Move(ctx, req.(*MoveIORequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MoveService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "moveio.MoveService",
	HandlerType: (*MoveServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Move",
			Handler:    _MoveService_Move_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/move.proto",
}

func init() { proto.RegisterFile("protobuf/move.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0xcf, 0xcd, 0x2f, 0x4b, 0xd5, 0x03, 0xf3, 0x84, 0xd8, 0x40, 0xec,
	0xcc, 0x7c, 0x29, 0x99, 0xf4, 0xfc, 0xfc, 0xf4, 0x9c, 0x54, 0xfd, 0xc4, 0x82, 0x4c, 0xfd, 0xc4,
	0xbc, 0xbc, 0xfc, 0x92, 0xc4, 0x92, 0xcc, 0xfc, 0xbc, 0x62, 0x88, 0x2a, 0x25, 0x65, 0x2e, 0x5e,
	0xdf, 0xfc, 0xb2, 0x54, 0x4f, 0xff, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x21, 0x2e,
	0x96, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b, 0x49, 0x87,
	0x8b, 0x0f, 0xa6, 0xa8, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55, 0x48, 0x8a, 0x8b, 0xa3, 0x08, 0xca,
	0x86, 0xaa, 0x84, 0xf3, 0x8d, 0xc2, 0xb8, 0xb8, 0x41, 0xaa, 0x83, 0x53, 0x8b, 0xca, 0x32, 0x93,
	0x53, 0x85, 0xdc, 0xb9, 0x58, 0x40, 0x5c, 0x21, 0x51, 0x3d, 0x88, 0x83, 0xf4, 0x50, 0xec, 0x93,
	0x12, 0x43, 0x17, 0x86, 0x98, 0xa2, 0x24, 0xd0, 0x74, 0xf9, 0xc9, 0x64, 0x26, 0x2e, 0x25, 0x56,
	0xb0, 0x9f, 0xac, 0x18, 0xb5, 0x92, 0xd8, 0xc0, 0x2e, 0x36, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff,
	0xfa, 0x23, 0xd8, 0x89, 0xee, 0x00, 0x00, 0x00,
}
