// Code generated by protoc-gen-go.
// source: protobuf/move.proto
// DO NOT EDIT!

/*
Package move is a generated protocol buffer package.

It is generated from these files:
	protobuf/move.proto

It has these top-level messages:
	Pipeline
	Gesture
	Hook
	Token
*/
package move

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Pipeline struct {
	Id          string      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	UserId      string      `protobuf:"bytes,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Description string      `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Next        []*Pipeline `protobuf:"bytes,4,rep,name=next" json:"next,omitempty"`
	GestureId   string      `protobuf:"bytes,5,opt,name=gesture_id,json=gestureId" json:"gesture_id,omitempty"`
	Timeout     int64       `protobuf:"varint,6,opt,name=timeout" json:"timeout,omitempty"`
	Name        string      `protobuf:"bytes,7,opt,name=name" json:"name,omitempty"`
	HookId      string      `protobuf:"bytes,8,opt,name=hook_id,json=hookId" json:"hook_id,omitempty"`
}

func (m *Pipeline) Reset()                    { *m = Pipeline{} }
func (m *Pipeline) String() string            { return proto.CompactTextString(m) }
func (*Pipeline) ProtoMessage()               {}
func (*Pipeline) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Pipeline) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Pipeline) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Pipeline) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Pipeline) GetNext() []*Pipeline {
	if m != nil {
		return m.Next
	}
	return nil
}

func (m *Pipeline) GetGestureId() string {
	if m != nil {
		return m.GestureId
	}
	return ""
}

func (m *Pipeline) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *Pipeline) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Pipeline) GetHookId() string {
	if m != nil {
		return m.HookId
	}
	return ""
}

type Gesture struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Meta        string `protobuf:"bytes,3,opt,name=meta" json:"meta,omitempty"`
	Name        string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
}

func (m *Gesture) Reset()                    { *m = Gesture{} }
func (m *Gesture) String() string            { return proto.CompactTextString(m) }
func (*Gesture) ProtoMessage()               {}
func (*Gesture) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Gesture) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Gesture) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Gesture) GetMeta() string {
	if m != nil {
		return m.Meta
	}
	return ""
}

func (m *Gesture) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Hook struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Format      string `protobuf:"bytes,2,opt,name=format" json:"format,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
}

func (m *Hook) Reset()                    { *m = Hook{} }
func (m *Hook) String() string            { return proto.CompactTextString(m) }
func (*Hook) ProtoMessage()               {}
func (*Hook) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Hook) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Hook) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *Hook) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Hook) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Token struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *Token) Reset()                    { *m = Token{} }
func (m *Token) String() string            { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()               {}
func (*Token) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*Pipeline)(nil), "Pipeline")
	proto.RegisterType((*Gesture)(nil), "Gesture")
	proto.RegisterType((*Hook)(nil), "Hook")
	proto.RegisterType((*Token)(nil), "Token")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Auths service

type AuthsClient interface {
	Auth(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Token, error)
}

type authsClient struct {
	cc *grpc.ClientConn
}

func NewAuthsClient(cc *grpc.ClientConn) AuthsClient {
	return &authsClient{cc}
}

func (c *authsClient) Auth(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := grpc.Invoke(ctx, "/Auths/Auth", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auths service

type AuthsServer interface {
	Auth(context.Context, *Token) (*Token, error)
}

func RegisterAuthsServer(s *grpc.Server, srv AuthsServer) {
	s.RegisterService(&_Auths_serviceDesc, srv)
}

func _Auths_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthsServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auths/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthsServer).Auth(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auths_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Auths",
	HandlerType: (*AuthsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth",
			Handler:    _Auths_Auth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/move.proto",
}

// Client API for Gestures service

type GesturesClient interface {
	CreateGesture(ctx context.Context, in *Gesture, opts ...grpc.CallOption) (*Gesture, error)
	GetGesture(ctx context.Context, in *Gesture, opts ...grpc.CallOption) (*Gesture, error)
	GetAllGesture(ctx context.Context, in *Gesture, opts ...grpc.CallOption) (*Gesture, error)
	DeleteGesture(ctx context.Context, in *Gesture, opts ...grpc.CallOption) (*Gesture, error)
}

type gesturesClient struct {
	cc *grpc.ClientConn
}

func NewGesturesClient(cc *grpc.ClientConn) GesturesClient {
	return &gesturesClient{cc}
}

func (c *gesturesClient) CreateGesture(ctx context.Context, in *Gesture, opts ...grpc.CallOption) (*Gesture, error) {
	out := new(Gesture)
	err := grpc.Invoke(ctx, "/Gestures/CreateGesture", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gesturesClient) GetGesture(ctx context.Context, in *Gesture, opts ...grpc.CallOption) (*Gesture, error) {
	out := new(Gesture)
	err := grpc.Invoke(ctx, "/Gestures/GetGesture", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gesturesClient) GetAllGesture(ctx context.Context, in *Gesture, opts ...grpc.CallOption) (*Gesture, error) {
	out := new(Gesture)
	err := grpc.Invoke(ctx, "/Gestures/GetAllGesture", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gesturesClient) DeleteGesture(ctx context.Context, in *Gesture, opts ...grpc.CallOption) (*Gesture, error) {
	out := new(Gesture)
	err := grpc.Invoke(ctx, "/Gestures/DeleteGesture", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Gestures service

type GesturesServer interface {
	CreateGesture(context.Context, *Gesture) (*Gesture, error)
	GetGesture(context.Context, *Gesture) (*Gesture, error)
	GetAllGesture(context.Context, *Gesture) (*Gesture, error)
	DeleteGesture(context.Context, *Gesture) (*Gesture, error)
}

func RegisterGesturesServer(s *grpc.Server, srv GesturesServer) {
	s.RegisterService(&_Gestures_serviceDesc, srv)
}

func _Gestures_CreateGesture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Gesture)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GesturesServer).CreateGesture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Gestures/CreateGesture",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GesturesServer).CreateGesture(ctx, req.(*Gesture))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gestures_GetGesture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Gesture)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GesturesServer).GetGesture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Gestures/GetGesture",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GesturesServer).GetGesture(ctx, req.(*Gesture))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gestures_GetAllGesture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Gesture)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GesturesServer).GetAllGesture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Gestures/GetAllGesture",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GesturesServer).GetAllGesture(ctx, req.(*Gesture))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gestures_DeleteGesture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Gesture)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GesturesServer).DeleteGesture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Gestures/DeleteGesture",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GesturesServer).DeleteGesture(ctx, req.(*Gesture))
	}
	return interceptor(ctx, in, info, handler)
}

var _Gestures_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Gestures",
	HandlerType: (*GesturesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGesture",
			Handler:    _Gestures_CreateGesture_Handler,
		},
		{
			MethodName: "GetGesture",
			Handler:    _Gestures_GetGesture_Handler,
		},
		{
			MethodName: "GetAllGesture",
			Handler:    _Gestures_GetAllGesture_Handler,
		},
		{
			MethodName: "DeleteGesture",
			Handler:    _Gestures_DeleteGesture_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/move.proto",
}

// Client API for Pipelines service

type PipelinesClient interface {
	CreatePipeline(ctx context.Context, in *Pipeline, opts ...grpc.CallOption) (*Pipeline, error)
	GetPipeline(ctx context.Context, in *Pipeline, opts ...grpc.CallOption) (*Pipeline, error)
	GetAllPipeline(ctx context.Context, in *Pipeline, opts ...grpc.CallOption) (*Pipeline, error)
	DeletePipeline(ctx context.Context, in *Pipeline, opts ...grpc.CallOption) (*Pipeline, error)
}

type pipelinesClient struct {
	cc *grpc.ClientConn
}

func NewPipelinesClient(cc *grpc.ClientConn) PipelinesClient {
	return &pipelinesClient{cc}
}

func (c *pipelinesClient) CreatePipeline(ctx context.Context, in *Pipeline, opts ...grpc.CallOption) (*Pipeline, error) {
	out := new(Pipeline)
	err := grpc.Invoke(ctx, "/Pipelines/CreatePipeline", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelinesClient) GetPipeline(ctx context.Context, in *Pipeline, opts ...grpc.CallOption) (*Pipeline, error) {
	out := new(Pipeline)
	err := grpc.Invoke(ctx, "/Pipelines/GetPipeline", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelinesClient) GetAllPipeline(ctx context.Context, in *Pipeline, opts ...grpc.CallOption) (*Pipeline, error) {
	out := new(Pipeline)
	err := grpc.Invoke(ctx, "/Pipelines/GetAllPipeline", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelinesClient) DeletePipeline(ctx context.Context, in *Pipeline, opts ...grpc.CallOption) (*Pipeline, error) {
	out := new(Pipeline)
	err := grpc.Invoke(ctx, "/Pipelines/DeletePipeline", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Pipelines service

type PipelinesServer interface {
	CreatePipeline(context.Context, *Pipeline) (*Pipeline, error)
	GetPipeline(context.Context, *Pipeline) (*Pipeline, error)
	GetAllPipeline(context.Context, *Pipeline) (*Pipeline, error)
	DeletePipeline(context.Context, *Pipeline) (*Pipeline, error)
}

func RegisterPipelinesServer(s *grpc.Server, srv PipelinesServer) {
	s.RegisterService(&_Pipelines_serviceDesc, srv)
}

func _Pipelines_CreatePipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pipeline)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelinesServer).CreatePipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Pipelines/CreatePipeline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelinesServer).CreatePipeline(ctx, req.(*Pipeline))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pipelines_GetPipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pipeline)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelinesServer).GetPipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Pipelines/GetPipeline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelinesServer).GetPipeline(ctx, req.(*Pipeline))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pipelines_GetAllPipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pipeline)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelinesServer).GetAllPipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Pipelines/GetAllPipeline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelinesServer).GetAllPipeline(ctx, req.(*Pipeline))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pipelines_DeletePipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pipeline)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelinesServer).DeletePipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Pipelines/DeletePipeline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelinesServer).DeletePipeline(ctx, req.(*Pipeline))
	}
	return interceptor(ctx, in, info, handler)
}

var _Pipelines_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Pipelines",
	HandlerType: (*PipelinesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePipeline",
			Handler:    _Pipelines_CreatePipeline_Handler,
		},
		{
			MethodName: "GetPipeline",
			Handler:    _Pipelines_GetPipeline_Handler,
		},
		{
			MethodName: "GetAllPipeline",
			Handler:    _Pipelines_GetAllPipeline_Handler,
		},
		{
			MethodName: "DeletePipeline",
			Handler:    _Pipelines_DeletePipeline_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/move.proto",
}

func init() { proto.RegisterFile("protobuf/move.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 498 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x53, 0xc1, 0x8a, 0xd3, 0x50,
	0x14, 0x25, 0x69, 0xda, 0x26, 0xb7, 0x24, 0x8e, 0x77, 0xc6, 0x31, 0x14, 0x07, 0xca, 0x5b, 0x95,
	0x2e, 0x1a, 0xac, 0x88, 0x5a, 0x45, 0x18, 0x14, 0x6a, 0x77, 0x52, 0xdc, 0x4b, 0x66, 0x72, 0xa7,
	0x7d, 0x34, 0xc9, 0x0b, 0xc9, 0x8b, 0x08, 0xe2, 0x42, 0x7f, 0xc1, 0x4f, 0x73, 0xe7, 0xda, 0x0f,
	0xf0, 0x13, 0x24, 0x2f, 0x2f, 0xe9, 0xd8, 0x42, 0xc7, 0x55, 0xce, 0xbd, 0x2f, 0xe7, 0x9c, 0x7b,
	0x5e, 0x6e, 0xe0, 0x34, 0xcb, 0x85, 0x14, 0x57, 0xe5, 0x4d, 0x90, 0x88, 0x4f, 0x34, 0x55, 0xd5,
	0xf0, 0xd1, 0x5a, 0x88, 0x75, 0x4c, 0x41, 0x98, 0xf1, 0x20, 0x4c, 0x53, 0x21, 0x43, 0xc9, 0x45,
	0x5a, 0xd4, 0xa7, 0xec, 0x97, 0x01, 0xf6, 0x7b, 0x9e, 0x51, 0xcc, 0x53, 0x42, 0x0f, 0x4c, 0x1e,
	0xf9, 0xc6, 0xc8, 0x18, 0x3b, 0x2b, 0x93, 0x47, 0xf8, 0x10, 0xfa, 0x65, 0x41, 0xf9, 0x47, 0x1e,
	0xf9, 0xa6, 0x6a, 0xf6, 0xaa, 0x72, 0x19, 0xe1, 0x08, 0x06, 0x11, 0x15, 0xd7, 0x39, 0xcf, 0x2a,
	0x2d, 0xbf, 0xa3, 0x0e, 0x6f, 0xb7, 0xf0, 0x02, 0xac, 0x94, 0x3e, 0x4b, 0xdf, 0x1a, 0x75, 0xc6,
	0x83, 0x99, 0x33, 0x6d, 0x3c, 0x56, 0xaa, 0x8d, 0x17, 0x00, 0x6b, 0x2a, 0x64, 0x99, 0x53, 0x25,
	0xde, 0x55, 0x7c, 0x47, 0x77, 0x96, 0x11, 0xfa, 0xd0, 0x97, 0x3c, 0x21, 0x51, 0x4a, 0xbf, 0x37,
	0x32, 0xc6, 0x9d, 0x55, 0x53, 0x22, 0x82, 0x95, 0x86, 0x09, 0xf9, 0x7d, 0x45, 0x51, 0xb8, 0x1a,
	0x73, 0x23, 0xc4, 0xb6, 0x52, 0xb2, 0xeb, 0x31, 0xab, 0x72, 0x19, 0xb1, 0x6b, 0xe8, 0x2f, 0x6a,
	0xcd, 0x83, 0x68, 0x7b, 0x09, 0xcc, 0xc3, 0x04, 0x08, 0x56, 0x42, 0x32, 0xd4, 0xe1, 0x14, 0x6e,
	0xdd, 0xad, 0x9d, 0x3b, 0x8b, 0xc0, 0x7a, 0x27, 0xc4, 0xf6, 0xc0, 0xe1, 0x1c, 0x7a, 0x37, 0x22,
	0x4f, 0x42, 0xd9, 0xdc, 0x5d, 0x5d, 0xb5, 0x1a, 0x9d, 0x5b, 0x09, 0xf6, 0xa6, 0xb1, 0x0e, 0xa6,
	0x61, 0x17, 0xd0, 0xfd, 0x20, 0xb6, 0x94, 0xe2, 0x19, 0x74, 0x65, 0x05, 0xb4, 0x53, 0x5d, 0xcc,
	0x1e, 0x43, 0xf7, 0xb2, 0x94, 0x9b, 0x02, 0xc7, 0x60, 0x55, 0x00, 0x7b, 0x53, 0xf5, 0xfa, 0x50,
	0x3f, 0xd9, 0xc9, 0xf7, 0x9f, 0xbf, 0x7f, 0x98, 0xc0, 0xba, 0x41, 0x58, 0xca, 0xcd, 0xdc, 0x98,
	0xcc, 0xfe, 0x18, 0x60, 0xeb, 0xdb, 0x29, 0xf0, 0x39, 0xb8, 0x6f, 0x72, 0x0a, 0x25, 0x35, 0xf7,
	0x65, 0x4f, 0x35, 0x1a, 0xb6, 0x88, 0x9d, 0x2a, 0x0d, 0x97, 0xd9, 0x81, 0xfe, 0x52, 0x73, 0x63,
	0x82, 0xcf, 0x00, 0x16, 0x24, 0x8f, 0xd1, 0x1e, 0x28, 0xda, 0x3d, 0x74, 0x1b, 0x5a, 0xf0, 0x85,
	0x47, 0x5f, 0xf1, 0x29, 0xb8, 0x0b, 0x92, 0x97, 0x71, 0x7c, 0x8c, 0xab, 0xc7, 0xc6, 0xd6, 0x12,
	0xe7, 0xe0, 0xbe, 0xa5, 0x98, 0x8e, 0x4f, 0xaa, 0x2d, 0x27, 0xff, 0x5a, 0xce, 0xbe, 0x99, 0xe0,
	0x34, 0x8b, 0x58, 0xe0, 0x2b, 0xf0, 0xea, 0xcc, 0xed, 0xfe, 0xef, 0xd6, 0x74, 0xb8, 0x83, 0xec,
	0x4c, 0x89, 0x79, 0xcc, 0x09, 0x32, 0xdd, 0xaa, 0x72, 0xbf, 0x84, 0xc1, 0x82, 0xe4, 0x1d, 0xd4,
	0x73, 0x45, 0x3d, 0x41, 0xaf, 0xa5, 0xd6, 0xd9, 0x5f, 0x80, 0x57, 0x67, 0xbf, 0x83, 0x7f, 0x5f,
	0xf1, 0x07, 0xb8, 0xb3, 0xc6, 0xd7, 0xe0, 0xd5, 0xf9, 0xff, 0xcf, 0x7a, 0xb2, 0x67, 0x7d, 0xd5,
	0x53, 0xff, 0xfd, 0x93, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6c, 0xc8, 0x4a, 0x27, 0x2c, 0x04,
	0x00, 0x00,
}
