// Code generated by protoc-gen-go.
// source: protobuf/move.proto
// DO NOT EDIT!

/*
Package move is a generated protocol buffer package.

It is generated from these files:
	protobuf/move.proto

It has these top-level messages:
	Pipeline
	Gesture
	Gestures
	Pipelines
	GestureMessage
	Hook
	Token
*/
package move

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Pipeline struct {
	Id          string      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	UserId      string      `protobuf:"bytes,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Description string      `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Next        []*Pipeline `protobuf:"bytes,4,rep,name=next" json:"next,omitempty"`
	GestureId   string      `protobuf:"bytes,5,opt,name=gesture_id,json=gestureId" json:"gesture_id,omitempty"`
	Timeout     int64       `protobuf:"varint,6,opt,name=timeout" json:"timeout,omitempty"`
	Name        string      `protobuf:"bytes,7,opt,name=name" json:"name,omitempty"`
	HookId      string      `protobuf:"bytes,8,opt,name=hook_id,json=hookId" json:"hook_id,omitempty"`
}

func (m *Pipeline) Reset()                    { *m = Pipeline{} }
func (m *Pipeline) String() string            { return proto.CompactTextString(m) }
func (*Pipeline) ProtoMessage()               {}
func (*Pipeline) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Pipeline) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Pipeline) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Pipeline) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Pipeline) GetNext() []*Pipeline {
	if m != nil {
		return m.Next
	}
	return nil
}

func (m *Pipeline) GetGestureId() string {
	if m != nil {
		return m.GestureId
	}
	return ""
}

func (m *Pipeline) GetTimeout() int64 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (m *Pipeline) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Pipeline) GetHookId() string {
	if m != nil {
		return m.HookId
	}
	return ""
}

type Gesture struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Meta        string `protobuf:"bytes,3,opt,name=meta" json:"meta,omitempty"`
	Name        string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	UserId      string `protobuf:"bytes,5,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *Gesture) Reset()                    { *m = Gesture{} }
func (m *Gesture) String() string            { return proto.CompactTextString(m) }
func (*Gesture) ProtoMessage()               {}
func (*Gesture) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Gesture) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Gesture) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Gesture) GetMeta() string {
	if m != nil {
		return m.Meta
	}
	return ""
}

func (m *Gesture) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Gesture) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type Gestures struct {
	Gestures []*Gesture `protobuf:"bytes,1,rep,name=gestures" json:"gestures,omitempty"`
}

func (m *Gestures) Reset()                    { *m = Gestures{} }
func (m *Gestures) String() string            { return proto.CompactTextString(m) }
func (*Gestures) ProtoMessage()               {}
func (*Gestures) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Gestures) GetGestures() []*Gesture {
	if m != nil {
		return m.Gestures
	}
	return nil
}

type Pipelines struct {
	Pipelines []*Pipeline `protobuf:"bytes,1,rep,name=pipelines" json:"pipelines,omitempty"`
}

func (m *Pipelines) Reset()                    { *m = Pipelines{} }
func (m *Pipelines) String() string            { return proto.CompactTextString(m) }
func (*Pipelines) ProtoMessage()               {}
func (*Pipelines) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Pipelines) GetPipelines() []*Pipeline {
	if m != nil {
		return m.Pipelines
	}
	return nil
}

type GestureMessage struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Meta   string `protobuf:"bytes,2,opt,name=meta" json:"meta,omitempty"`
}

func (m *GestureMessage) Reset()                    { *m = GestureMessage{} }
func (m *GestureMessage) String() string            { return proto.CompactTextString(m) }
func (*GestureMessage) ProtoMessage()               {}
func (*GestureMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GestureMessage) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GestureMessage) GetMeta() string {
	if m != nil {
		return m.Meta
	}
	return ""
}

type Hook struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Format      string `protobuf:"bytes,2,opt,name=format" json:"format,omitempty"`
	Name        string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
}

func (m *Hook) Reset()                    { *m = Hook{} }
func (m *Hook) String() string            { return proto.CompactTextString(m) }
func (*Hook) ProtoMessage()               {}
func (*Hook) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Hook) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Hook) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *Hook) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Hook) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Token struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *Token) Reset()                    { *m = Token{} }
func (m *Token) String() string            { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()               {}
func (*Token) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*Pipeline)(nil), "Pipeline")
	proto.RegisterType((*Gesture)(nil), "Gesture")
	proto.RegisterType((*Gestures)(nil), "Gestures")
	proto.RegisterType((*Pipelines)(nil), "Pipelines")
	proto.RegisterType((*GestureMessage)(nil), "GestureMessage")
	proto.RegisterType((*Hook)(nil), "Hook")
	proto.RegisterType((*Token)(nil), "Token")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Auths service

type AuthsClient interface {
	Auth(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Token, error)
}

type authsClient struct {
	cc *grpc.ClientConn
}

func NewAuthsClient(cc *grpc.ClientConn) AuthsClient {
	return &authsClient{cc}
}

func (c *authsClient) Auth(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := grpc.Invoke(ctx, "/Auths/Auth", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auths service

type AuthsServer interface {
	Auth(context.Context, *Token) (*Token, error)
}

func RegisterAuthsServer(s *grpc.Server, srv AuthsServer) {
	s.RegisterService(&_Auths_serviceDesc, srv)
}

func _Auths_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthsServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Auths/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthsServer).Auth(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auths_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Auths",
	HandlerType: (*AuthsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Auth",
			Handler:    _Auths_Auth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/move.proto",
}

// Client API for GesturesServ service

type GesturesServClient interface {
	CreateGesture(ctx context.Context, in *Gesture, opts ...grpc.CallOption) (*Gesture, error)
	GetGesture(ctx context.Context, in *Gesture, opts ...grpc.CallOption) (*Gesture, error)
	GetAllGesture(ctx context.Context, in *Gesture, opts ...grpc.CallOption) (*Gestures, error)
	DeleteGesture(ctx context.Context, in *Gesture, opts ...grpc.CallOption) (*Gesture, error)
}

type gesturesServClient struct {
	cc *grpc.ClientConn
}

func NewGesturesServClient(cc *grpc.ClientConn) GesturesServClient {
	return &gesturesServClient{cc}
}

func (c *gesturesServClient) CreateGesture(ctx context.Context, in *Gesture, opts ...grpc.CallOption) (*Gesture, error) {
	out := new(Gesture)
	err := grpc.Invoke(ctx, "/GesturesServ/CreateGesture", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gesturesServClient) GetGesture(ctx context.Context, in *Gesture, opts ...grpc.CallOption) (*Gesture, error) {
	out := new(Gesture)
	err := grpc.Invoke(ctx, "/GesturesServ/GetGesture", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gesturesServClient) GetAllGesture(ctx context.Context, in *Gesture, opts ...grpc.CallOption) (*Gestures, error) {
	out := new(Gestures)
	err := grpc.Invoke(ctx, "/GesturesServ/GetAllGesture", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gesturesServClient) DeleteGesture(ctx context.Context, in *Gesture, opts ...grpc.CallOption) (*Gesture, error) {
	out := new(Gesture)
	err := grpc.Invoke(ctx, "/GesturesServ/DeleteGesture", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GesturesServ service

type GesturesServServer interface {
	CreateGesture(context.Context, *Gesture) (*Gesture, error)
	GetGesture(context.Context, *Gesture) (*Gesture, error)
	GetAllGesture(context.Context, *Gesture) (*Gestures, error)
	DeleteGesture(context.Context, *Gesture) (*Gesture, error)
}

func RegisterGesturesServServer(s *grpc.Server, srv GesturesServServer) {
	s.RegisterService(&_GesturesServ_serviceDesc, srv)
}

func _GesturesServ_CreateGesture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Gesture)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GesturesServServer).CreateGesture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GesturesServ/CreateGesture",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GesturesServServer).CreateGesture(ctx, req.(*Gesture))
	}
	return interceptor(ctx, in, info, handler)
}

func _GesturesServ_GetGesture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Gesture)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GesturesServServer).GetGesture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GesturesServ/GetGesture",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GesturesServServer).GetGesture(ctx, req.(*Gesture))
	}
	return interceptor(ctx, in, info, handler)
}

func _GesturesServ_GetAllGesture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Gesture)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GesturesServServer).GetAllGesture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GesturesServ/GetAllGesture",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GesturesServServer).GetAllGesture(ctx, req.(*Gesture))
	}
	return interceptor(ctx, in, info, handler)
}

func _GesturesServ_DeleteGesture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Gesture)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GesturesServServer).DeleteGesture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GesturesServ/DeleteGesture",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GesturesServServer).DeleteGesture(ctx, req.(*Gesture))
	}
	return interceptor(ctx, in, info, handler)
}

var _GesturesServ_serviceDesc = grpc.ServiceDesc{
	ServiceName: "GesturesServ",
	HandlerType: (*GesturesServServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGesture",
			Handler:    _GesturesServ_CreateGesture_Handler,
		},
		{
			MethodName: "GetGesture",
			Handler:    _GesturesServ_GetGesture_Handler,
		},
		{
			MethodName: "GetAllGesture",
			Handler:    _GesturesServ_GetAllGesture_Handler,
		},
		{
			MethodName: "DeleteGesture",
			Handler:    _GesturesServ_DeleteGesture_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/move.proto",
}

// Client API for PipelinesServ service

type PipelinesServClient interface {
	CreatePipeline(ctx context.Context, in *Pipeline, opts ...grpc.CallOption) (*Pipeline, error)
	GetPipeline(ctx context.Context, in *Pipeline, opts ...grpc.CallOption) (*Pipeline, error)
	GetAllPipeline(ctx context.Context, in *Pipeline, opts ...grpc.CallOption) (*Pipelines, error)
	DeletePipeline(ctx context.Context, in *Pipeline, opts ...grpc.CallOption) (*Pipeline, error)
}

type pipelinesServClient struct {
	cc *grpc.ClientConn
}

func NewPipelinesServClient(cc *grpc.ClientConn) PipelinesServClient {
	return &pipelinesServClient{cc}
}

func (c *pipelinesServClient) CreatePipeline(ctx context.Context, in *Pipeline, opts ...grpc.CallOption) (*Pipeline, error) {
	out := new(Pipeline)
	err := grpc.Invoke(ctx, "/PipelinesServ/CreatePipeline", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelinesServClient) GetPipeline(ctx context.Context, in *Pipeline, opts ...grpc.CallOption) (*Pipeline, error) {
	out := new(Pipeline)
	err := grpc.Invoke(ctx, "/PipelinesServ/GetPipeline", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelinesServClient) GetAllPipeline(ctx context.Context, in *Pipeline, opts ...grpc.CallOption) (*Pipelines, error) {
	out := new(Pipelines)
	err := grpc.Invoke(ctx, "/PipelinesServ/GetAllPipeline", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelinesServClient) DeletePipeline(ctx context.Context, in *Pipeline, opts ...grpc.CallOption) (*Pipeline, error) {
	out := new(Pipeline)
	err := grpc.Invoke(ctx, "/PipelinesServ/DeletePipeline", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PipelinesServ service

type PipelinesServServer interface {
	CreatePipeline(context.Context, *Pipeline) (*Pipeline, error)
	GetPipeline(context.Context, *Pipeline) (*Pipeline, error)
	GetAllPipeline(context.Context, *Pipeline) (*Pipelines, error)
	DeletePipeline(context.Context, *Pipeline) (*Pipeline, error)
}

func RegisterPipelinesServServer(s *grpc.Server, srv PipelinesServServer) {
	s.RegisterService(&_PipelinesServ_serviceDesc, srv)
}

func _PipelinesServ_CreatePipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pipeline)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelinesServServer).CreatePipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PipelinesServ/CreatePipeline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelinesServServer).CreatePipeline(ctx, req.(*Pipeline))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelinesServ_GetPipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pipeline)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelinesServServer).GetPipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PipelinesServ/GetPipeline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelinesServServer).GetPipeline(ctx, req.(*Pipeline))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelinesServ_GetAllPipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pipeline)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelinesServServer).GetAllPipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PipelinesServ/GetAllPipeline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelinesServServer).GetAllPipeline(ctx, req.(*Pipeline))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelinesServ_DeletePipeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pipeline)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelinesServServer).DeletePipeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PipelinesServ/DeletePipeline",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelinesServServer).DeletePipeline(ctx, req.(*Pipeline))
	}
	return interceptor(ctx, in, info, handler)
}

var _PipelinesServ_serviceDesc = grpc.ServiceDesc{
	ServiceName: "PipelinesServ",
	HandlerType: (*PipelinesServServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePipeline",
			Handler:    _PipelinesServ_CreatePipeline_Handler,
		},
		{
			MethodName: "GetPipeline",
			Handler:    _PipelinesServ_GetPipeline_Handler,
		},
		{
			MethodName: "GetAllPipeline",
			Handler:    _PipelinesServ_GetAllPipeline_Handler,
		},
		{
			MethodName: "DeletePipeline",
			Handler:    _PipelinesServ_DeletePipeline_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/move.proto",
}

// Client API for RequestGestureServ service

type RequestGestureServClient interface {
	PostGesture(ctx context.Context, in *GestureMessage, opts ...grpc.CallOption) (*GestureMessage, error)
}

type requestGestureServClient struct {
	cc *grpc.ClientConn
}

func NewRequestGestureServClient(cc *grpc.ClientConn) RequestGestureServClient {
	return &requestGestureServClient{cc}
}

func (c *requestGestureServClient) PostGesture(ctx context.Context, in *GestureMessage, opts ...grpc.CallOption) (*GestureMessage, error) {
	out := new(GestureMessage)
	err := grpc.Invoke(ctx, "/RequestGestureServ/PostGesture", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RequestGestureServ service

type RequestGestureServServer interface {
	PostGesture(context.Context, *GestureMessage) (*GestureMessage, error)
}

func RegisterRequestGestureServServer(s *grpc.Server, srv RequestGestureServServer) {
	s.RegisterService(&_RequestGestureServ_serviceDesc, srv)
}

func _RequestGestureServ_PostGesture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GestureMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RequestGestureServServer).PostGesture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RequestGestureServ/PostGesture",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RequestGestureServServer).PostGesture(ctx, req.(*GestureMessage))
	}
	return interceptor(ctx, in, info, handler)
}

var _RequestGestureServ_serviceDesc = grpc.ServiceDesc{
	ServiceName: "RequestGestureServ",
	HandlerType: (*RequestGestureServServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostGesture",
			Handler:    _RequestGestureServ_PostGesture_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/move.proto",
}

func init() { proto.RegisterFile("protobuf/move.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 609 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0x1d, 0x27, 0xb1, 0x27, 0xd8, 0x2d, 0xd3, 0x52, 0xac, 0x88, 0x4a, 0xd1, 0x0a, 0x89,
	0x28, 0x87, 0x18, 0x02, 0x02, 0x14, 0x3e, 0xa4, 0x8a, 0x4a, 0xa1, 0x07, 0xa4, 0x2a, 0x70, 0xe2,
	0x82, 0x5c, 0x3c, 0x4d, 0xad, 0x24, 0xde, 0xe0, 0x5d, 0x57, 0x48, 0xc0, 0x85, 0x03, 0x7f, 0x80,
	0x9f, 0xc6, 0x8d, 0x33, 0x7f, 0x81, 0x3b, 0xf2, 0xda, 0xeb, 0x7c, 0xa1, 0xc2, 0xa9, 0xf3, 0xd1,
	0x37, 0x6f, 0xde, 0xdb, 0x71, 0x60, 0x6f, 0x91, 0x72, 0xc9, 0xcf, 0xb2, 0xf3, 0x60, 0xce, 0x2f,
	0xa9, 0xaf, 0xb2, 0xf6, 0xad, 0x09, 0xe7, 0x93, 0x19, 0x05, 0xe1, 0x22, 0x0e, 0xc2, 0x24, 0xe1,
	0x32, 0x94, 0x31, 0x4f, 0x44, 0xd1, 0x65, 0x3f, 0x0d, 0xb0, 0x4f, 0xe3, 0x05, 0xcd, 0xe2, 0x84,
	0xd0, 0x03, 0x33, 0x8e, 0x7c, 0xa3, 0x63, 0x74, 0x9d, 0xb1, 0x19, 0x47, 0x78, 0x13, 0x9a, 0x99,
	0xa0, 0xf4, 0x5d, 0x1c, 0xf9, 0xa6, 0x2a, 0x36, 0xf2, 0xf4, 0x24, 0xc2, 0x0e, 0xb4, 0x22, 0x12,
	0xef, 0xd3, 0x78, 0x91, 0xcf, 0xf2, 0x6b, 0xaa, 0xb9, 0x5a, 0xc2, 0x43, 0xb0, 0x12, 0xfa, 0x28,
	0x7d, 0xab, 0x53, 0xeb, 0xb6, 0x06, 0x4e, 0x5f, 0x73, 0x8c, 0x55, 0x19, 0x0f, 0x01, 0x26, 0x24,
	0x64, 0x96, 0x52, 0x3e, 0xbc, 0xae, 0xf0, 0x4e, 0x59, 0x39, 0x89, 0xd0, 0x87, 0xa6, 0x8c, 0xe7,
	0xc4, 0x33, 0xe9, 0x37, 0x3a, 0x46, 0xb7, 0x36, 0xd6, 0x29, 0x22, 0x58, 0x49, 0x38, 0x27, 0xbf,
	0xa9, 0x20, 0x2a, 0xce, 0xd7, 0xbc, 0xe0, 0x7c, 0x9a, 0x4f, 0xb2, 0x8b, 0x35, 0xf3, 0xf4, 0x24,
	0x62, 0x9f, 0xa1, 0x39, 0x2a, 0x66, 0x6e, 0x49, 0xdb, 0x50, 0x60, 0x6e, 0x2b, 0x40, 0xb0, 0xe6,
	0x24, 0xc3, 0x52, 0x9c, 0x8a, 0x2b, 0x76, 0x6b, 0x9d, 0x5d, 0x9b, 0x54, 0x5f, 0x35, 0x89, 0xdd,
	0x05, 0xbb, 0x64, 0x17, 0x78, 0x1b, 0xec, 0x52, 0x9d, 0xf0, 0x0d, 0x65, 0x89, 0xdd, 0x2f, 0x9b,
	0xe3, 0xaa, 0xc3, 0x1e, 0x80, 0xa3, 0x7d, 0x12, 0x78, 0x07, 0x9c, 0x85, 0x4e, 0x4a, 0xcc, 0x8a,
	0x8d, 0xcb, 0x1e, 0x7b, 0x06, 0x5e, 0x39, 0xea, 0x15, 0x09, 0x11, 0x4e, 0xd6, 0x56, 0x32, 0xd6,
	0xde, 0x4d, 0x6b, 0x32, 0x97, 0x9a, 0x58, 0x04, 0xd6, 0x4b, 0xce, 0xa7, 0x5b, 0x0e, 0x1d, 0x40,
	0xe3, 0x9c, 0xa7, 0xf3, 0x50, 0xea, 0xb7, 0x2f, 0xb2, 0xca, 0x83, 0xda, 0x8a, 0x07, 0x1b, 0x6e,
	0x5a, 0x5b, 0x6e, 0xb2, 0x43, 0xa8, 0xbf, 0xe1, 0x53, 0x4a, 0x70, 0x1f, 0xea, 0x32, 0x0f, 0x4a,
	0xa6, 0x22, 0x19, 0xdc, 0x83, 0xfa, 0x51, 0x26, 0x2f, 0x04, 0x76, 0xc1, 0xca, 0x03, 0x6c, 0xf4,
	0xd5, 0xbf, 0xb7, 0xcb, 0xbf, 0x6c, 0xf7, 0xeb, 0x8f, 0x5f, 0xdf, 0x4d, 0x60, 0xf5, 0x20, 0xcc,
	0xe4, 0xc5, 0xd0, 0xe8, 0x0d, 0x7e, 0x1b, 0x70, 0x4d, 0xfb, 0xfb, 0x9a, 0xd2, 0x4b, 0x7c, 0x0c,
	0xee, 0x8b, 0x94, 0x42, 0x49, 0xfa, 0xcd, 0x2b, 0x8b, 0xdb, 0x55, 0xc4, 0xf6, 0xd4, 0x1c, 0x97,
	0xd9, 0x41, 0xe9, 0xfa, 0xd0, 0xe8, 0xe1, 0x23, 0x80, 0x11, 0xc9, 0xab, 0x60, 0x37, 0x14, 0x6c,
	0x07, 0x5d, 0x0d, 0x0b, 0x3e, 0xc5, 0xd1, 0x17, 0x7c, 0x08, 0xee, 0x88, 0xe4, 0xd1, 0x6c, 0xb6,
	0x8d, 0x75, 0x74, 0x24, 0xf4, 0xee, 0x58, 0x71, 0xe2, 0x10, 0xdc, 0x63, 0x9a, 0xd1, 0xd5, 0xab,
	0x96, 0x9c, 0xbd, 0x75, 0xce, 0xc1, 0x37, 0x13, 0xdc, 0xea, 0x4a, 0x94, 0xf0, 0xa7, 0xe0, 0x15,
	0xc2, 0xab, 0x0f, 0x79, 0x79, 0x28, 0xed, 0x65, 0xc8, 0xf6, 0xd5, 0x40, 0x8f, 0x39, 0x81, 0x3e,
	0x9e, 0x5c, 0xfc, 0x13, 0x68, 0x8d, 0x48, 0xfe, 0x03, 0x7a, 0xa0, 0xa0, 0xbb, 0xe8, 0x55, 0xd0,
	0xc2, 0x80, 0x61, 0x7e, 0x7b, 0xb9, 0x01, 0x7f, 0xc3, 0x43, 0x15, 0x0a, 0x76, 0x5d, 0x0d, 0x68,
	0xe1, 0x92, 0x1b, 0x9f, 0x83, 0x57, 0x98, 0xf0, 0x7f, 0xdc, 0xbd, 0x0d, 0xee, 0xc1, 0x5b, 0xc0,
	0x31, 0x7d, 0xc8, 0x48, 0xe8, 0x97, 0x53, 0x66, 0x1c, 0x43, 0xeb, 0x94, 0x57, 0x25, 0xdc, 0xe9,
	0xaf, 0x7f, 0x1b, 0xed, 0xcd, 0xc2, 0xca, 0x45, 0xa4, 0xc5, 0xb4, 0xa1, 0xd1, 0x3b, 0x6b, 0xa8,
	0x5f, 0xc7, 0xfb, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xf3, 0x47, 0x3c, 0xab, 0x52, 0x05, 0x00,
	0x00,
}
